version: 1.0.{build}

branches:
  only:
    - master
    - develop
    
image: Visual Studio 2017

platform: Any CPU

configuration: 
    - Release
    - Debug
    
before_build:
    - nuget restore
    
build:
    verbosity: minimal
    publish_wap: true